// Podplane <https://podplane.dev>
// Copyright The Podplane Authors
// SPDX-License-Identifier: Apache-2.0

package tfgen

import (
	"fmt"
	"os"
	"path/filepath"
)

const header = `# Podplane managed OpenTofu/Terraform file.
# Do not edit this file directly. Update the Podplane JSONC config then rerun the Podplane CLI command, or update user-owned Terraform variable files.

`

// File is one managed Terraform file to write.
type File struct {
	Name    string
	Content string
}

// WriteFiles writes managed Terraform files with the Podplane header.
func WriteFiles(dir string, files []File) error {
	for _, file := range files {
		if file.Name == "" {
			return fmt.Errorf("generated tf file name is empty")
		}
		path := filepath.Join(dir, file.Name)
		content := header + file.Content
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}
