// Podplane <https://podplane.dev>
// Copyright The Podplane Authors
// SPDX-License-Identifier: Apache-2.0

package tfgen

import (
	"fmt"
	"os"
	"path/filepath"
)

const header = `# Podplane managed OpenTofu/Terraform file.
# Do not edit this file directly. Update the Podplane JSONC config then rerun the Podplane CLI command, or update user-owned Terraform variable files.

`

// FileType identifies the syntax and header behavior of a generated file.
type FileType int

const (
	FileTypeTerraform FileType = iota + 1
	FileTypeJSON
)

// File is one generated infrastructure file to write.
type File struct {
	Name    string
	Content string
	Type    FileType
}

// WriteFiles writes generated files, adding the Podplane header to Terraform.
func WriteFiles(dir string, files []File) error {
	for _, file := range files {
		if file.Name == "" {
			return fmt.Errorf("generated tf file name is empty")
		}
		path := filepath.Join(dir, file.Name)
		content := file.Content
		switch file.Type {
		case FileTypeTerraform:
			content = header + content
		case FileTypeJSON:
		default:
			return fmt.Errorf("generated file %s has unsupported type %d", file.Name, file.Type)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}
